package:
  name: django-tastypie
  version: "0.10.0"

source:
  fn: django-tastypie-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/d/django-tastypie/django-tastypie-0.10.0.tar.gz
  md5: 03009279f547483085f58057d5052a65
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-tastypie = django-tastypie:main
    #
    # Would create an entry point called django-tastypie that calls django-tastypie.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=1.5,!=2.0

  run:
    - python
    - python-dateutil >=1.5,!=2.0

test:
  # Python imports
  imports:
    - tastypie
    - tastypie.contrib
    - tastypie.contrib.contenttypes
    - tastypie.contrib.gis
    - tastypie.management
    - tastypie.management.commands
    - tastypie.migrations
 #   - tastypie.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/toastdriven/django-tastypie/
  license: BSD License
  summary: 'A flexible & capable API layer for Django.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
