package:
  name: chembl_core_model
  version: "0.6.2"

source:
  fn: chembl_core_model-0.6.2.tar.gz
  url: https://pypi.python.org/packages/source/c/chembl_core_model/chembl_core_model-0.6.2.tar.gz
  md5: 38e0384e1e67e5309e2ae81606d2061a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - chembl_core_model = chembl_core_model:main
    #
    # Would create an entry point called chembl_core_model that calls chembl_core_model.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - chembl_core_db >=0.6.2
    - pyyaml

  run:
    - python
    - chembl_core_db >=0.6.2
    - pyyaml

test:
  # Python imports
 # imports:
 #   - chembl_core_model
 #   - chembl_core_model.models

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://www.ebi.ac.uk/chembl/
  license: Apache Software License
  summary: 'Core ChEMBL python ORM model'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
